### ISSUE TITLE
fileVersion seems to be based on version

### ISSUE THREAD

**Issue by chkalch** [kit-data-manager/base-repo#216]
When uploading a new version of a file, fileVersion jumps to the current version (or previous version + 1). Maybe this is intentional but at first glance it seems to be a bug.

**To Reproduce**

1. Upload a file to a resource (replace ID with appropriate value):
`curl 'http://127.0.0.1:8090/api/v1/dataresources/<ID>/data/test.txt' -i -X POST -H 'Content-Type: multipart/form-data' -F 'file=@test.txt;type=multipart/form-data'`

2. Patch the metadata of the file (replace ETAG with value from previous response):

```
curl 'http://127.0.0.1:8090/api/v1/dataresources/<ID>/data/test.txt' -i -X PATCH \
    -H 'Content-Type: application/json-patch+json' \
    -H 'If-Match: "<ETAG>"' \
    -d '[ {
  "op" : "add",
  "path" : "/tags/-",
  "value" : "test"
} ]'
```

3. Check version and fileVersion using a get request:

`curl 'http://127.0.0.1:8090/api/v1/dataresources/<ID>/data/test.txt' -i -X GET -H 'Accept: application/vnd.datamanager.content-information+json'`

Result will be: version = 2 and fileVersion = 1

4. Repeat step 1

5. Repeat step 3

Result will be: version = 3 and fileVersion = 3

**Expected behavior**

fileVersion only increments by one when uploading a new version of the file.

In the case mentioned previously result would have been: version = 3 and fileVersion = 2.

**Version (output of actuator/info)**

```
{
"git": {
  "branch": "main",
  "commit": {
    "id": "4e90c6a",
    "time": "2023-07-31T11:21:49Z"
  }
  },
  "build": {
    "artifact": "base-repo",
    "name": "base-repo",
    "time": "2023-12-13T15:17:52.545Z",
    "version": "1.4.1-SNAPSHOT"
  }
}
```

**Comment by ThomasJejkal** [comment]
Well, this is indeed a bit confusing, but I think I've found the reason behind (maybe you can confirm if I'm correct). 

Typically, metadata and file version should work as described by you. Overwriting an existing content location should increase the file version, while updating only the metadata should increase the metadataVersion only. Now I came across the following line in the code: 

https://github.com/kit-data-manager/repo-core/blob/c3be40470ff2b3b5e84a67d58a49fe73bdcd7ffd/src/main/java/edu/kit/datamanager/repo/service/impl/ContentInformationService.java#L258

There it says, that if the versioning service (which is responsible to write files) does not return a new file version number, the version number of the metadata is used instead. In my opinion this is a bug. I assume, that the configured versioning service returns no new version number because nothing is written as the old and the new file were identical. This is not handled properly. Could you please confirm this behaviour by uploading the same file (then metadata and file version should be "aligned") and a different file (then, file version should be bigger than metadata version).

**Comment by ThomasJejkal** [comment]
https://github.com/kit-data-manager/repo-core/issues/270

**Comment by ThomasJejkal** [comment]
At the end, this was a bit of a bigger issue as the use of fileVersion was a bit misleading. Actually, the fileVersion is not intended to be accessed by the user. It is only used internally by specific versioning service implementations (currently one, which is not part of the default distribution). For all other implementations, fileVersion is not evaluated such that the file version is coupled to the metadata version which is provided via the version query parameter.

In the next release, the current behaviour will be changed in the sense, that fileVersion is fixed to '1' if not managed by the versioning service implementation. In the initial example this would mean at the end a metadata version of '3' and a file version of '1'. Repeating step 1 at this point will increase the metadata version to '4', but the file version will stay at '1'.
