### ISSUE TITLE
Search for state REVOKED returns VOLATILE and FIXED

### ISSUE THREAD

**Issue by chkalch** [kit-data-manager/base-repo#235]
When searching for state REVOKED the results contain resources with state VOLATILE and FIXED but not with state REVOKED.

**To Reproduce**

Change the state of a resource to REVOKED or create a new resource like so:

```
curl 'http://localhost:8090/api/v1/dataresources/' -i -X POST \
    -H 'Content-Type: application/json' \
    -d '{
            "creators" : [{
            "familyName" : "Doe",
            "givenName" : "John"
        }],
        "titles" : [{
            "value" : "Most basic resource for testing"
        }],
        "resourceType" : {
            "value" : "testingSample",
            "typeGeneral" : "DATASET"
        },
        "state" : "REVOKED"
    }'
```

The response should confirm that a resource with state == REVOKED exists.

Now search for resources with state == REVOKED like so:

```
curl 'http://localhost:8090/api/v1/dataresources/search' -i -X POST \
    -H 'Content-Type: application/json' \
    -d '{
        "state" : "REVOKED"
    }'
```

The result contains all (as far as they exist) resources with state VOLATILE as well as with state FIXED.

On the other hand searches for state VOLATILE, FIXED or GONE returns resources where the state ist set as expected.

**Expected behavior**
Search for state == REVOKED only returns resources with appropriate state.

**Version**
Tested version 1.4.1-SNAPSHOT as well as 1.5.4-SNAPSHOT with no obvious difference.

**Comment by ThomasJejkal** [comment]
Well, the state attribute is a bit special when it comes to search. The reason is, that the state is used to determine whether a resource is visible to a user or not. As you probably know, there are the four states VOLATILE, FIXED, REVOKED, and GONE. Only VOLATILE and FIXED resources are visible to users, typically a resources is created in state VOLATILE and may or may not move to FIXED. 

If a resource is deleted, which can be done by someone with ADMINISTRATE permissions (typically the owner), the resource enters the state REVOKED. In this state, the resource is only returned to users with role ADMINISTRATOR, who can then either patch the state back to VOLATILE/FIXED or delete the resource again to enter the state GONE (which also implies that all data is deleted).  

Due to these restrictions it is internally enforced, that filtering for REVOKED resources is only performed if the caller has the role ADMINISTRATOR. Otherwise, the state is handled as if it was empty, i.e., filters for VOLATILE and FIXED are applied. Instead, if you provide FIXED as state in your search, only resources in state FIXED are returned.

You now may ask how it is possible assign the ADMINISTRATOR role for search...well, as I assume that you are not using authentication at all, i.e., only use the SELF identity, there is currently no way to do so, mainly for security reasons. Assigning the ADMINISTRATOR role is only possible when using external JSON Web Tokens issued by a KeyCloak instance.

**Comment by chkalch** [comment]
OK, I understand, thank you for the explanation.
